// Property test for build_tool_call_grammar: every output the grammar admits must be accepted by
// parse_qwen36_tool_output for the same request, with the tool_choice contract kept. Constrained
// decoding is only as good as that implication -- a grammar that admits one output the parser
// refuses turns a 502 we removed back into a 502.
//
// Outputs are produced by random walks through xgrammar's token masks over a small raw vocabulary:
// every byte (so free text and string values reach every character, including '<' and newlines),
// the protocol delimiters and near misses ("<tools>", "<tool"), JSON pieces, and the names the
// corpus uses. Walks favour multi-character tokens so they reach the end of long structures.
#include "chat_tools.hpp"
#include "tool_grammar.hpp"

#include <nlohmann/json.hpp>

#include <cstdio>
#include <cstdlib>
#include <map>
#include <random>
#include <set>
#include <string>
#include <vector>

namespace {

using nlohmann::json;
using sparkinfer_server::ChatRequest;
using sparkinfer_server::GrammarEngine;
using sparkinfer_server::ParsedToolOutput;
using sparkinfer_server::ToolCallGrammar;
using sparkinfer_server::ToolChoiceMode;
using sparkinfer_server::build_response_format_grammar;
using sparkinfer_server::build_tool_call_grammar;
using sparkinfer_server::parse_plain_assistant_output;
using sparkinfer_server::validate_response_format;
using sparkinfer_server::parse_chat_request_json;
using sparkinfer_server::parse_qwen36_tool_output;

int g_failures = 0;

#define CHECK(expr)                                                                            \
    do {                                                                                       \
        if (!(expr)) {                                                                         \
            std::fprintf(stderr, "FAIL: %s:%d: %s\n", __FILE__, __LINE__, #expr);             \
            ++g_failures;                                                                      \
        }                                                                                      \
    } while (0)

// What the server's detokenizer does to generated bytes (HF ByteLevel decoding is UTF-8 lossy): each
// maximal invalid subsequence becomes U+FFFD. A byte-level vocabulary can emit a lone continuation
// byte; the parser never sees it raw, so neither may this test.
std::string utf8_lossy(const std::string& in) {
    static const std::string kReplacement = "\xef\xbf\xbd";
    std::string out;
    size_t i = 0;
    const size_t n = in.size();
    auto byte = [&](size_t k) { return static_cast<unsigned char>(in[k]); };
    while (i < n) {
        const unsigned char c = byte(i);
        if (c < 0x80) { out.push_back(static_cast<char>(c)); ++i; continue; }
        int len = 0;
        unsigned char lo = 0x80, hi = 0xBF;
        if (c >= 0xC2 && c <= 0xDF) len = 2;
        else if (c == 0xE0) { len = 3; lo = 0xA0; }
        else if ((c >= 0xE1 && c <= 0xEC) || c == 0xEE || c == 0xEF) len = 3;
        else if (c == 0xED) { len = 3; hi = 0x9F; }
        else if (c == 0xF0) { len = 4; lo = 0x90; }
        else if (c >= 0xF1 && c <= 0xF3) len = 4;
        else if (c == 0xF4) { len = 4; hi = 0x8F; }
        if (len == 0) { out += kReplacement; ++i; continue; }
        size_t k = 1;
        for (; k < static_cast<size_t>(len) && i + k < n; ++k) {
            const unsigned char b = byte(i + k);
            if (k == 1 ? (b < lo || b > hi) : (b < 0x80 || b > 0xBF)) break;
        }
        if (k == static_cast<size_t>(len)) out.append(in, i, len);
        else out += kReplacement;
        i += k;
    }
    return out;
}

struct Vocab {
    std::vector<std::string> tokens;
    int stop = -1;
};

Vocab make_vocab(const std::set<std::string>& words) {
    Vocab v;
    for (int b = 1; b < 256; ++b) v.tokens.push_back(std::string(1, static_cast<char>(b)));
    std::set<std::string> extra = {
        "<tool_call>", "</tool_call>", "<think>", "</think>", "</think>\n\n", "<function=", "</function>",
        "<parameter=", "</parameter>", "\n</parameter>\n", ">\n", "\n", "\n\n", "<tool", "<tools>",
        "<|im_start|>", "<|im_", "</tool_response>", "true", "false", "null", "{\"", "\": ", "\"", ", ",
        "0", "12", "-3", "2.5", "1e3", "[", "]", "{", "}", "Paris", "hello world", "\xc3\xa9", "\xe6\x97\xa5",
        "\\n", "\\\"", "   "};
    extra.insert(words.begin(), words.end());
    for (const std::string& s : extra)
        if (s.size() > 1) v.tokens.push_back(s);
    v.tokens.push_back("<|im_end|>");
    v.stop = static_cast<int>(v.tokens.size()) - 1;
    return v;
}

// One walk through the production constraint (grammar mask AND UTF-8 mask). True when it reached a
// stop within the step budget; `text` is the output without the stop token. A step with no allowed
// token is a grammar dead end and fails.
bool walk(GrammarEngine& engine, const std::string& tag, const Vocab& vocab, std::mt19937& rng, std::string& text) {
    bool exact = true;
    std::string err;
    auto constraint = engine.make_constraint(tag, exact, err);
    if (!constraint) {
        std::fprintf(stderr, "no constraint: %s\n", err.c_str());
        ++g_failures;
        return false;
    }
    const int vocab_size = static_cast<int>(vocab.tokens.size());
    std::vector<uint32_t> bits((vocab_size + 31) / 32);
    text.clear();
    for (int step = 0; step < 900; ++step) {
        constraint->fill_next_mask(bits.data(), vocab_size);
        std::vector<int> allowed, multi;
        for (int id = 0; id < vocab_size; ++id) {
            if (!((bits[id / 32] >> (id % 32)) & 1)) continue;
            allowed.push_back(id);
            if (id != vocab.stop && vocab.tokens[id].size() > 1) multi.push_back(id);
        }
        if (allowed.empty()) {
            std::fprintf(stderr, "dead end after %zu bytes: %s\n", text.size(), text.c_str());
            ++g_failures;
            return false;
        }
        // Speculative decoding walks a drafted path ahead and rolls it back: afterwards the mask
        // must be exactly the one before.
        if (rng() % 3 == 0) {
            const std::vector<uint32_t> before = bits;
            std::vector<uint32_t> ahead(bits.size());
            int walked = 0;
            for (int k = 0, depth = 1 + rng() % 7; k < depth; ++k) {
                constraint->fill_next_mask(ahead.data(), vocab_size);
                std::vector<int> ok;
                for (int id = 0; id < vocab_size; ++id)
                    if (((ahead[id / 32] >> (id % 32)) & 1) && id != vocab.stop) ok.push_back(id);
                if (ok.empty() || !constraint->accept(ok[rng() % ok.size()])) break;
                ++walked;
            }
            if (!constraint->can_rollback() || !constraint->rollback(walked)) {
                std::fprintf(stderr, "rollback(%d) failed\n", walked);
                ++g_failures;
                return false;
            }
            constraint->fill_next_mask(ahead.data(), vocab_size);
            if (ahead != before) {
                std::fprintf(stderr, "mask after rollback(%d) differs from the mask before\n", walked);
                ++g_failures;
                return false;
            }
        }
        const bool can_stop = (bits[vocab.stop / 32] >> (vocab.stop % 32)) & 1;
        int pick;
        if (can_stop && (rng() % 4 == 0 || step > 600)) pick = vocab.stop;
        else if (!multi.empty() && (rng() % 3 != 0 || step > 450)) pick = multi[rng() % multi.size()];
        else pick = allowed[rng() % allowed.size()];
        if (!constraint->accept(pick)) {
            std::fprintf(stderr, "constraint refused a token its own mask allowed\n");
            ++g_failures;
            return false;
        }
        if (pick == vocab.stop) return true;
        text += vocab.tokens[pick];
    }
    return false;
}

// Feeds `text` byte by byte through a fresh constraint, then a stop. The vocabulary holds every byte.
bool admits(GrammarEngine& engine, const std::string& tag, const Vocab& vocab, const std::string& text) {
    bool exact = true;
    std::string err;
    auto constraint = engine.make_constraint(tag, exact, err);
    if (!constraint) return false;
    const int vocab_size = static_cast<int>(vocab.tokens.size());
    std::vector<uint32_t> bits((vocab_size + 31) / 32);
    auto step = [&](int id) {
        constraint->fill_next_mask(bits.data(), vocab_size);
        return ((bits[id / 32] >> (id % 32)) & 1) && constraint->accept(id);
    };
    for (unsigned char c : text)
        if (c == 0 || !step(static_cast<int>(c) - 1)) return false;   // byte b is token b - 1
    return step(vocab.stop);
}

struct Case {
    std::string name;
    std::string body;   // chat request JSON
    bool thinking;
};

// The corpus: every schema keyword the server accepts, every tool_choice mode, both parallel settings,
// thinking on and off.
std::vector<Case> corpus() {
    const std::string weather = R"({"type":"function","function":{"name":"get_weather","parameters":{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}}})";
    const std::string time = R"({"type":"function","function":{"name":"get_time","parameters":{"type":"object","properties":{"tz":{"type":"string","enum":["UTC","Europe/Paris"]},"offset":{"type":"integer","minimum":-12,"maximum":14}},"required":["tz"]}}})";
    const std::string kitchen = R"({"type":"function","function":{"name":"kitchen_sink","parameters":{
      "type":"object",
      "$defs":{"Guest":{"type":"object","properties":{"name":{"type":"string","minLength":1},"age":{"type":"integer","minimum":0}},"required":["name"],"additionalProperties":false}},
      "properties":{
        "count":{"type":"integer","minimum":1,"maximum":9,"multipleOf":2},
        "ratio":{"type":"number","exclusiveMinimum":0,"maximum":1},
        "flag":{"type":"boolean"},
        "nothing":{"type":"null"},
        "tags":{"type":"array","items":{"type":"string","maxLength":8},"minItems":1,"maxItems":3},
        "pair":{"type":"array","prefixItems":[{"type":"integer"},{"type":"string"}]},
        "guest":{"$ref":"#/$defs/Guest"},
        "guests":{"type":"array","items":{"$ref":"#/$defs/Guest"}},
        "code":{"type":"string","pattern":"^[A-Z]{3}$"},
        "slug":{"type":"string","pattern":"[a-z]+-[0-9]"},
        "dotted":{"type":"string","pattern":"^a.c$"},
        "short":{"type":"string","minLength":2,"maxLength":4},
        "capped":{"type":"string","maxLength":5},
        "mode":{"const":"fast"},
        "either":{"anyOf":[{"type":"string","maxLength":3},{"type":"integer"}]},
        "one":{"oneOf":[{"type":"integer","minimum":10},{"type":"boolean"}]},
        "both":{"allOf":[{"type":"integer"},{"minimum":5}]},
        "note":{"type":"string"}
      },
      "required":["count","code","guest"]}}})";
    const std::string empty = R"({"type":"function","function":{"name":"ping","parameters":{"type":"object","properties":{}}}})";
    auto req = [](const std::string& tools, const std::string& extra) {
        return std::string(R"({"messages":[{"role":"user","content":"go"}],"tools":[)") + tools + "]" + extra + "}";
    };
    std::vector<Case> cases;
    for (bool thinking : {false, true}) {
        const std::string t = thinking ? " thinking" : "";
        cases.push_back({"auto weather" + t, req(weather, ""), thinking});
        cases.push_back({"auto 3 tools" + t, req(weather + "," + time + "," + empty, ""), thinking});
        cases.push_back({"required 2 tools" + t, req(weather + "," + time, R"(,"tool_choice":"required")"), thinking});
        cases.push_back({"required no parallel" + t, req(weather + "," + time, R"(,"tool_choice":"required","parallel_tool_calls":false)"), thinking});
        cases.push_back({"named" + t, req(weather + "," + time, R"(,"tool_choice":{"type":"function","function":{"name":"get_time"}})"), thinking});
        cases.push_back({"kitchen sink required" + t, req(kitchen, R"(,"tool_choice":"required")"), thinking});
        cases.push_back({"kitchen sink auto" + t, req(kitchen + "," + empty, ""), thinking});
    }
    return cases;
}

std::set<std::string> corpus_words() {
    return {"{\"answer\": ", "\"answer\"", "\"items\"", "\"score\"", "\"label\"", "\"html\"", "<b>", "</b>",
            "\"tier\"", "\"rooms\"", "\"note\"", "\"code\"","<tool_call>\n<function=get_weather>\n", "<tool_call>\n<function=get_time>\n",
            "<tool_call>\n<function=kitchen_sink>\n", "<tool_call>\n<function=ping>\n",
            "</function>\n</tool_call>", "<parameter=city>\n", "<parameter=tz>\n", "<parameter=offset>\n",
            "<parameter=count>\n", "<parameter=ratio>\n", "<parameter=flag>\n", "<parameter=nothing>\n",
            "<parameter=tags>\n", "<parameter=pair>\n", "<parameter=guest>\n", "<parameter=guests>\n",
            "<parameter=code>\n", "<parameter=slug>\n", "<parameter=dotted>\n", "<parameter=short>\n",
            "<parameter=capped>\n", "<parameter=mode>\n", "<parameter=either>\n", "<parameter=one>\n",
            "<parameter=both>\n", "<parameter=note>\n", "UTC", "Europe/Paris", "fast", "{\"name\": \"Ada\"}",
            "\"name\"", "\"age\"", "ABC", "abc-1", "a-9"};
}

void test_property(const Case& c, GrammarEngine& engine, const Vocab& vocab) {
    ChatRequest request;
    std::string err;
    CHECK(parse_chat_request_json(c.body, request, err));
    if (!err.empty()) {
        std::fprintf(stderr, "%s: request rejected: %s\n", c.name.c_str(), err.c_str());
        return;
    }
    ToolCallGrammar grammar;
    if (!build_tool_call_grammar(request, c.thinking, grammar, err)) {
        std::fprintf(stderr, "%s: no grammar: %s\n", c.name.c_str(), err.c_str());
        ++g_failures;
        return;
    }
    {
        std::string compile_err;
        bool exact = grammar.exact;
        if (!engine.make_constraint(grammar.structural_tag, exact, compile_err)) {
            std::fprintf(stderr, "%s: grammar does not compile: %s\n", c.name.c_str(), compile_err.c_str());
            ++g_failures;
            return;
        }
        if (!exact && grammar.exact) {
            grammar.exact = false;
            grammar.approximation = "a JSON value's string class could not be narrowed";
        }
    }
    std::mt19937 rng(12345);
    int finished = 0, accepted = 0, with_calls = 0, refused = 0;
    std::map<std::string, int> reasons;
    std::map<std::string, std::string> exact_reason_sample;   // full reason (with names) -> one output
    const bool demand = request.tool_choice == ToolChoiceMode::kRequired || request.tool_choice == ToolChoiceMode::kNamed;
    for (int i = 0; i < 400; ++i) {
        std::string text;
        if (!walk(engine, grammar.structural_tag, vocab, rng, text)) continue;
        ++finished;
        CHECK(utf8_lossy(text) == text);   // the UTF-8 mask keeps output valid
        const ParsedToolOutput out = parse_qwen36_tool_output(text, c.thinking, request);
        if (!out.error.empty()) {
            std::string reason = out.error;
            for (const char* p : {"parameter ", "function "}) {   // group by kind, not by name
                size_t at = reason.find(p);
                if (at != std::string::npos) {
                    size_t end = reason.find(' ', at + std::char_traits<char>::length(p));
                    reason.replace(at, (end == std::string::npos ? reason.size() : end) - at, std::string(p) + "X");
                }
            }
            ++reasons[reason];
            if (!exact_reason_sample.count(out.error)) exact_reason_sample[out.error] = utf8_lossy(text);
            if (++refused <= 3)
                std::fprintf(stderr, "%s%s: grammar output refused by the parser: %s\n---\n%s\n---\n",
                             c.name.c_str(), grammar.exact ? "" : " (approximate grammar)",
                             out.error.c_str(), utf8_lossy(text).substr(0, 1200).c_str());
            if (grammar.exact) ++g_failures;
            continue;
        }
        ++accepted;
        if (!out.tool_calls.empty()) ++with_calls;
        if (demand) CHECK(!out.tool_calls.empty());
        if (!request.parallel_tool_calls) CHECK(out.tool_calls.size() <= 1);
        if (request.tool_choice == ToolChoiceMode::kNamed)
            for (const auto& call : out.tool_calls) CHECK(call.name == request.required_tool_name);
    }
    std::printf("  %-32s exact=%d finished %3d/400, parsed %3d, refused %3d, with calls %3d%s%s\n",
                c.name.c_str(), grammar.exact, finished, accepted, refused, with_calls,
                grammar.exact ? "" : " -- ", grammar.approximation.c_str());
    for (const auto& [reason, count] : reasons) std::printf("      %4d x %s\n", count, reason.c_str());
    if (std::getenv("TOOL_GRAMMAR_SAMPLES")) {
        for (const auto& [reason, sample] : exact_reason_sample) {
            // Show the offending parameter when the reason names one.
            size_t at = std::string::npos;
            size_t name_at = reason.find("parameter ");
            if (name_at != std::string::npos) {
                const std::string name = reason.substr(name_at + 10, reason.find(' ', name_at + 10) - name_at - 10);
                at = sample.find("<parameter=" + name + ">");
            }
            if (at == std::string::npos) at = sample.find("<tool_call>");
            if (at == std::string::npos) at = 0;
            std::printf("    SAMPLE [%s]\n%s\n    END\n", reason.c_str(), sample.substr(at, 500).c_str());
        }
    }
    // Coverage, not correctness: a corpus the walks cannot finish proves nothing.
    CHECK(finished >= 40);
    if (demand) CHECK(with_calls >= 40);
}

// Hand-written outputs the grammar must refuse, and ones it must admit.
void test_boundaries(GrammarEngine& engine, const Vocab& vocab) {
    ChatRequest request;
    std::string err;
    CHECK(parse_chat_request_json(corpus()[4].body, request, err));   // named get_time, thinking off
    ToolCallGrammar grammar;
    CHECK(build_tool_call_grammar(request, false, grammar, err));
    const std::string& tag = grammar.structural_tag;
    const std::string call = "<tool_call>\n<function=get_time>\n<parameter=offset>\n2\n</parameter>\n<parameter=tz>\nUTC\n</parameter>\n</function>\n</tool_call>";
    CHECK(admits(engine, tag, vocab, call));
    CHECK(!admits(engine, tag, vocab, ""));                                             // named demands a call
    CHECK(!admits(engine, tag, vocab, "Sure." + call));                                 // no prose around it
    CHECK(!admits(engine, tag, vocab, "<tool_call>\n<function=get_weather>\n<parameter=city>\nParis\n</parameter>\n</function>\n</tool_call>"));
    CHECK(!admits(engine, tag, vocab, "<tool_call>\n<function=get_time>\n<parameter=tz>\nCET\n</parameter>\n</function>\n</tool_call>"));   // enum
    CHECK(!admits(engine, tag, vocab, "<tool_call>\n<function=get_time>\n<parameter=offset>\n20\n</parameter>\n<parameter=tz>\nUTC\n</parameter>\n</function>\n</tool_call>"));   // maximum
    CHECK(!admits(engine, tag, vocab, "<tool_call>\n<function=get_time>\n</function>\n</tool_call>"));   // tz is required
    CHECK(admits(engine, tag, vocab, call + "\n" + call));                              // parallel_tool_calls defaults to true
    CHECK(!admits(engine, tag, vocab, call + " bye"));                                  // nothing after the calls
    CHECK(!admits(engine, tag, vocab, "<tool_call>\n<function=get_time>\n<parameter=tz>\nUTC\n</parameter>x\n</parameter>\n</function>\n</tool_call>"));
    CHECK(!admits(engine, tag, vocab, "<tool_call>\n<function=get_time>\n<parameter=offset>\n\xe6\x97\n</parameter>\n<parameter=tz>\nUTC\n</parameter>\n</function>\n</tool_call>"));   // broken UTF-8

    // A JSON-typed argument keeps '<' -- only '<' that starts protocol markup is refused.
    ChatRequest rule_request;
    CHECK(parse_chat_request_json(R"({"messages":[{"role":"user","content":"go"}],"tool_choice":"required","tools":[{"type":"function","function":{"name":"save_rule","parameters":{"type":"object","properties":{"rule":{"type":"object","properties":{"expr":{"type":"string"}},"required":["expr"]}},"required":["rule"]}}}]})",
                                  rule_request, err));
    ToolCallGrammar rule_grammar;
    CHECK(build_tool_call_grammar(rule_request, false, rule_grammar, err));
    auto rule_call = [](const std::string& expr) {
        return "<tool_call>\n<function=save_rule>\n<parameter=rule>\n{\"expr\": \"" + expr + "\"}\n</parameter>\n</function>\n</tool_call>";
    };
    CHECK(admits(engine, rule_grammar.structural_tag, vocab, rule_call("x < 10 and y <= 3")));
    CHECK(admits(engine, rule_grammar.structural_tag, vocab, rule_call("<b>bold</b> <<to")));
    CHECK(!admits(engine, rule_grammar.structural_tag, vocab, rule_call("call <tool_call> now")));
    CHECK(!admits(engine, rule_grammar.structural_tag, vocab, rule_call("a</parameter>b")));
    CHECK(!admits(engine, rule_grammar.structural_tag, vocab, rule_call("<|im_end|>")));
    CHECK(admits(engine, rule_grammar.structural_tag, vocab, rule_call("\\u003ctool is escaped")));

    // response_format with thinking on: a JSON string may hold '<', never a think marker.
    ChatRequest format_request;
    CHECK(parse_chat_request_json(R"({"messages":[{"role":"user","content":"go"}],"response_format":{"type":"json_schema","json_schema":{"name":"o","schema":{"type":"object","properties":{"html":{"type":"string"}},"required":["html"]}}}})",
                                  format_request, err));
    ToolCallGrammar format_grammar;
    CHECK(build_response_format_grammar(format_request, true, format_grammar, err));
    CHECK(format_grammar.exact);
    CHECK(admits(engine, format_grammar.structural_tag, vocab, "ok\n</think>\n\n{\"html\": \"<b>x</b> <think\"}"));
    CHECK(!admits(engine, format_grammar.structural_tag, vocab, "ok\n</think>\n\n{\"html\": \"a</think>b\"}"));
    CHECK(!admits(engine, format_grammar.structural_tag, vocab, "ok\n</think>\n\n{\"html\": 1e400}"));
}


struct FormatCase {
    std::string name;
    std::string body;
    bool thinking;
};

std::vector<FormatCase> format_corpus() {
    const std::string schema = R"({
      "type":"object",
      "$defs":{"Item":{"type":"object","properties":{"label":{"type":"string","maxLength":12},"score":{"type":"number","minimum":0,"maximum":1}},"required":["label"],"additionalProperties":false}},
      "properties":{
        "answer":{"type":"string"},
        "html":{"type":"string"},
        "items":{"type":"array","items":{"$ref":"#/$defs/Item"},"minItems":1,"maxItems":3},
        "rooms":{"type":"integer","minimum":2,"maximum":10,"multipleOf":2},
        "tier":{"allOf":[{"type":"integer"},{"minimum":1},{"maximum":3}]},
        "code":{"type":"string","enum":["A<B","C"]},
        "note":{"anyOf":[{"type":"string","maxLength":5},{"type":"null"}]}
      },
      "required":["answer","items","rooms","tier"]})";
    auto req = [](const std::string& format) {
        return std::string(R"({"messages":[{"role":"user","content":"go"}],"response_format":)") + format + "}";
    };
    std::vector<FormatCase> cases;
    for (bool thinking : {false, true}) {
        const std::string t = thinking ? " thinking" : "";
        cases.push_back({"json_object" + t, req(R"({"type":"json_object"})"), thinking});
        cases.push_back({"json_schema" + t, req(R"({"type":"json_schema","json_schema":{"name":"out","schema":)" + schema + "}}"), thinking});
    }
    return cases;
}

void test_format_property(const FormatCase& c, GrammarEngine& engine, const Vocab& vocab) {
    ChatRequest request;
    std::string err;
    if (!parse_chat_request_json(c.body, request, err)) {
        std::fprintf(stderr, "%s: request rejected: %s\n", c.name.c_str(), err.c_str());
        ++g_failures;
        return;
    }
    ToolCallGrammar grammar;
    if (!build_response_format_grammar(request, c.thinking, grammar, err)) {
        std::fprintf(stderr, "%s: no grammar: %s\n", c.name.c_str(), err.c_str());
        ++g_failures;
        return;
    }
    {
        bool exact = grammar.exact;
        if (!engine.make_constraint(grammar.structural_tag, exact, err)) {
            std::fprintf(stderr, "%s: grammar does not compile: %s\n", c.name.c_str(), err.c_str());
            ++g_failures;
            return;
        }
        if (!exact) grammar.exact = false;
    }
    std::mt19937 rng(777);
    int finished = 0, accepted = 0, refused = 0;
    std::map<std::string, int> reasons;
    for (int i = 0; i < 400; ++i) {
        std::string text;
        if (!walk(engine, grammar.structural_tag, vocab, rng, text)) continue;
        ++finished;
        CHECK(utf8_lossy(text) == text);
        const auto plain = parse_plain_assistant_output(text, c.thinking);
        std::string verr;
        if (!validate_response_format(plain.content, request.response_format, verr)) {
            ++reasons[verr];
            if (++refused <= 3)
                std::fprintf(stderr, "%s: grammar output refused by validate_response_format: %s\n---\n%s\n---\n",
                             c.name.c_str(), verr.c_str(), text.substr(0, 800).c_str());
            if (grammar.exact) ++g_failures;
            continue;
        }
        ++accepted;
    }
    std::printf("  %-32s exact=%d finished %3d/400, valid %3d, refused %3d%s%s\n", c.name.c_str(), grammar.exact,
                finished, accepted, refused, grammar.exact ? "" : " -- ", grammar.approximation.c_str());
    for (const auto& [reason, count] : reasons) std::printf("      %4d x %s\n", count, reason.c_str());
    CHECK(finished >= 40);
}

}  // namespace

int main() {
    std::set<std::string> words = corpus_words();
    Vocab vocab = make_vocab(words);
    GrammarEngine engine(vocab.tokens, static_cast<int>(vocab.tokens.size()), {vocab.stop});
    for (const Case& c : corpus()) test_property(c, engine, vocab);
    test_boundaries(engine, vocab);
    for (const FormatCase& c : format_corpus()) test_format_property(c, engine, vocab);
    if (g_failures) {
        std::printf("tool_grammar_test: %d failure(s)\n", g_failures);
        return 1;
    }
    std::printf("tool_grammar_test: OK\n");
    return 0;
}
